name: A simple demo workflow

# Trigger: körs vid push till main
on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Node.js version
        run: node --version

      - name: Check NPM version
        run: npm --version
